### ISSUE TITLE
关于SABO

### ISSUE THREAD

**Issue by nixcty** [0Acar0/SABO-VMD-SVR#1]
在运行SABO-VMD的main时，选择SampleEntropyCost函数会产生如下报错，请问该如何解决？
![1713406667342](https://github.com/0Acar0/SABO-VMD-SVR/assets/145451950/c7bab350-1eb0-4436-83ee-8638496d2213)

**Comment by 0Acar0** [comment]
我这边的源代码不存在这个问题，在调用“main”函数时，需要手动将向量导入matlab并将其名称修改为“da”（data的缩写）
当时由于表格太多，采用的是手动导入数据的方式。


以下是部分样本熵计算的说明，希望可以帮到你

%   计算给定时间序列数据的样本熵

%   样本熵在概念上类似于近似熵，但有以下区别：

%       1）样本熵不计算自匹配，通过在最后一步取对数，避免了可能出现的log(0)问题；

%       2）样本熵不像近似熵那样依赖数据的长度。

%   dim：嵌入维数(一般取1或者2)

%   r：相似容限( 通常取0.1*Std(data)~0.25*Std(data) )

%   data：时间序列数据，data须为1xN的矩阵

%   tau：下采样延迟时间（在默认值为1的情况下，可以忽略此项）










在 2024-04-18 10:19:10，"nixcty" ***@***.***> 写道：

在运行SABO-VMD的main时，选择SampleEntropyCost函数会产生如下报错，请问该如何解决？
1713406667342.png (view on web)

**Comment by nixcty** [comment]
> 我修改的源代码不存在这个问题，在调用“main”函数时，需要手动将导入matlab将其名称为“da”（数据的缩写）当时由于表格太多，采用的是手动导入以下是部分样本熵计算的说明，希望可以帮到你 % 计算给定时间序列数据的样本熵 % 样本熵在概念上模拟近似熵，但有以下区别： % 1）样本熵不计算自匹配，通过在最后一步取对数，避免了可能出现的log(0)问题； % 2）样本熵不像近似熵那样依赖数据的长度。 % dim：嵌入维数(一般取1或者2 ) % r：相似容量限制(通常取0.1*Std(data)~0.25*Std(data) ) % data：时间序列数据，数据须为1xN的矩阵 % tau：下采样延迟时间（在默认值1）在 2024-04-18 10:19:10，"nixcty" ***@***.***> 写道：在运行 SABO-VMD 的主要时，选择SampleEntropyCost函数会产生如下报错，请问如何解决？ 1713406667342.png (在网络上查看) — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您订阅了该主题。消息 ID：***@***.***>

好的，谢谢您的解答。
